### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ondsola** [tretum/Avorion-Obj-Converter#9]
I'm not expecting a reply here since the last time this was updated was many years ago, but I figured I'd give it a shot :)

When trying to convert a ship using the converter I simply get an error which appears as follows:

C:\WINDOWS\system32>py C:\Users\Username\Desktop\Avorion-Obj-Converter-0.1.2\AvObjConverter.py "Pursuit1"
Converting block with index 0, type = 6, look = 1 and up = 3
Traceback (most recent call last):
  File "C:\Users\Username\Desktop\Avorion-Obj-Converter-0.1.2\AvObjConverter.py", line 407, in <module>
    converter.convertToObj(os.path.join(path, ship_name + '.xml'), './out/' + ship_name + '.obj')
  File "C:\Users\Username\Desktop\Avorion-Obj-Converter-0.1.2\AvObjConverter.py", line 123, in convertToObj
    self.scene.addObject(convertBlockToObj(block))
  File "C:\Users\Username\Desktop\Avorion-Obj-Converter-0.1.2\AvObjConverter.py", line 104, in convertBlockToObj
    scene = parser.parseFile()
  File "C:\Users\Username\Desktop\Avorion-Obj-Converter-0.1.2\waveobjparser\ObjParser.py", line 11, in parseFile
    with open(self.source) as file:
FileNotFoundError: [Errno 2] No such file or directory: './objects/Cube.obj'

I am unsure if this is related to the fact that I could only get it to run by using "py" and then the path to the converter, rather than "python AvObjConverter.py" but any help would be appreciated

**Comment by wrathfulpapaya** [comment]
Hey! I managed to get this to work (at the very least I got a .obj file, I don't know if it the conversion is buggered but it didn't give me any errors upon producing the file). So the error it gave you and I previously is in regards to: 

FileNotFoundError: [Errno 2] No such file or directory: './objects/Cube.obj'

So all I had to do was create a folder named "out" inside the same directory containing the AvObjConverter.py, run the script after doing this and the .obj that you output *should* be dropped in there without issue :)

**Comment by Ondsola** [comment]
> Hey! I managed to get this to work (at the very least I got a .obj file, I don't know if it the conversion is buggered but it didn't give me any errors upon producing the file). So the error it gave you and I previously is in regards to:
> 
> FileNotFoundError: [Errno 2] No such file or directory: './objects/Cube.obj'
> 
> So all I had to do was create a folder named "out" inside the same directory containing the AvObjConverter.py, run the script after doing this and the .obj that you output _should_ be dropped in there without issue :)

Believe it or not, this still did not work for me, and I'm getting the same error. Ive kinda run out of ways to troubleshoot as Im not really familiar with python, but thanks for your help anyway :)
